(function () {
  var el = document.getElementById('site-footer');
  if (!el) return;
  el.outerHTML = [
    '<footer class="footer">',
    '  <div class="footer__top">',
    '    <div class="footer__brand">',
    '      <a href="/"><img class="footer__logo" src="/images/misc/logo-white.png" alt="Network Consultancy" width="1779" height="453" decoding="async" /></a>',
    '      <p class="footer__tagline">Expert network consultancy providing secure, scalable infrastructure solutions.</p>',
    '      <button type="button" class="footer__search" data-search-trigger aria-label="Search this site">',
    '        <span>Search this site</span>',
    '        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">',
    '          <circle cx="11" cy="11" r="8" stroke="#353535" stroke-width="2"/>',
    '          <path d="m21 21-4.35-4.35" stroke="#353535" stroke-width="2" stroke-linecap="round"/>',
    '        </svg>',
    '      </button>',
    '      <div class="footer__social">',
    '        <a href="#" aria-label="Facebook" target="_blank" rel="noopener" class="footer__social-link">',
    '          <svg width="52" height="39" viewBox="0 0 52 39" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">',
    '            <rect width="52" height="39" rx="19.5" fill="rgba(255,255,255,0.12)"/>',
    '            <path d="M28.5 20H26.5V27H23.5V20H22V17.5H23.5V16C23.5 14.34 24.34 13 26.5 13H28.5V15.5H27.5C26.95 15.5 26.5 15.78 26.5 16.5V17.5H28.5L28.5 20Z" fill="white"/>',
    '          </svg>',
    '        </a>',
    '        <a href="#" aria-label="LinkedIn" target="_blank" rel="noopener" class="footer__social-link">',
    '          <svg width="52" height="39" viewBox="0 0 52 39" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">',
    '            <rect width="52" height="39" rx="19.5" fill="rgba(255,255,255,0.12)"/>',
    '            <path d="M20 15.5C20 16.33 19.33 17 18.5 17C17.67 17 17 16.33 17 15.5C17 14.67 17.67 14 18.5 14C19.33 14 20 14.67 20 15.5ZM17 18.5H20V27H17V18.5ZM22 18.5H24.8V19.8H24.84C25.22 19.08 26.14 18.3 27.5 18.3C30.5 18.3 31 20.26 31 22.8V27H28V23.3C28 22.2 27.98 20.8 26.5 20.8C25 20.8 24.8 22 24.8 23.22V27H22V18.5Z" fill="white"/>',
    '          </svg>',
    '        </a>',
    '        <a href="#" aria-label="Twitter / X" target="_blank" rel="noopener" class="footer__social-link">',
    '          <svg width="52" height="39" viewBox="0 0 52 39" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">',
    '            <rect width="52" height="39" rx="19.5" fill="rgba(255,255,255,0.12)"/>',
    '            <path d="M30.96 14H33.28L28.18 19.77L34.18 26.97H29.45L25.79 22.18L21.59 26.97H19.26L24.71 20.81L18.96 14H23.8L27.12 18.37L30.96 14ZM30.16 25.57H31.44L23.04 15.31H21.67L30.16 25.57Z" fill="white"/>',
    '          </svg>',
    '        </a>',
    '      </div>',
    '      <div class="footer__badges">',
    '        <img src="/images/misc/badge-cyber-essentials.png" alt="Cyber Essentials Certified" class="footer__badge-cyber" width="330" height="396" decoding="async" />',
    '        <img src="/images/misc/badge-ukas.png" alt="URS UKAS Management Systems ISO 9001 Certified" class="footer__badge-ukas" width="122" height="122" decoding="async" />',
    '      </div>',
    '    </div>',
    '    <div class="footer__links">',
    '      <div class="footer__col">',
    '        <h4>Industries</h4>',
    '        <ul>',
    '          <li><a href="/industries/legal-firms">Legal Firms</a></li>',
    '          <li><a href="/industries/financial-services">Financial Services</a></li>',
    '          <li><a href="/industries/recruitment-agencies">Recruitment Agencies</a></li>',
    '          <li><a href="/industries/healthcare-and-clinics">Healthcare &amp; Clinics</a></li>',
    '          <li><a href="/industries/manufacturing">Manufacturing</a></li>',
    '          <li><a href="/industries/multi-site-businesses">Multi-Site Businesses</a></li>',
    '          <li><a href="/industries/internal-it-teams">Internal IT Teams / Co-Managed IT</a></li>',
    '        </ul>',
    '      </div>',
    '      <div class="footer__col">',
    '        <h4>Services</h4>',
    '        <ul>',
    '          <li><a href="/services/managed-wireless-lan">Managed Wireless LAN</a></li>',
    '          <li><a href="/services/business-continuity-and-network-resilience">Business Continuity &amp; Network</a></li>',
    '          <li><a href="/services/network-installations">Network Installations</a></li>',
    '          <li><a href="/services/network-consultancy">Network Consultancy</a></li>',
    '          <li><a href="/services/network-support">Network Support</a></li>',
    '          <li><a href="/services/managed-network-support">Managed Network Support</a></li>',
    '          <li><a href="/services/network-design-and-deployment">Network Design &amp; Deployment</a></li>',
    '          <li><a href="/services/remote-working-solutions">Remote Access &amp; VPN Solutions</a></li>',
    '          <li><a href="/services/firewall-and-network-security">Firewall &amp; Network Security</a></li>',
    '        </ul>',
    '      </div>',
    '      <div class="footer__col">',
    '        <h4>Solutions</h4>',
    '        <ul>',
    '          <li><a href="/solutions/network-health-check">Network Health Check</a></li>',
    '          <li><a href="/solutions/cyber-security-review">Cyber Security Review</a></li>',
    '          <li><a href="/solutions/microsoft-365-and-network-readiness">Microsoft 365 &amp; Network</a></li>',
    '          <li><a href="/solutions/ai-ready-infrastructure-review">AI-Ready Infrastructure Review</a></li>',
    '        </ul>',
    '        <h4 class="mt">Resources</h4>',
    '        <ul>',
    '          <li><a href="/case-studies/index">Case Studies</a></li>',
    '        </ul>',
    '      </div>',
    '    </div>',
    '  </div>',
    '  <hr class="footer__divider" />',
    '  <div class="footer__bottom">',
    '    <div class="footer__bottom-links">',
    '      <a href="/">Home</a>',
    '      <a href="/about">About</a>',
    '      <a href="/contact">Contact</a>',
    '      <a href="/privacy-policy">Privacy Policy</a>',
    '      <a href="/terms-of-service">Terms &amp; Conditions</a>',
    '      <a href="/cookie-policy">Cookie Policy</a>',
    '      <a href="/complaint-form">Complaint Form</a>',
    '    </div>',
    '    <p class="footer__copy">&copy; 2026 Network Consultancy is a trading name of Qcom.ltd. All Rights Reserved.</p>',
    '    <p class="footer__copy">Qcom.ltd is registered in England and Wales. Company Registration Number: 11862320. Registered Office: 20-22 Wenlock Rd, London, N1 7GU.</p>',
    '  </div>',
    '</footer>'
  ].join('\n');
})();
